import { boolean, numeric, pgTable, serial, text, timestamp } from 'drizzle-orm/pg-core'

export const user = pgTable('user', {
  id: text('id').primaryKey(), name: text('name').notNull(), email: text('email').notNull().unique(), emailVerified: boolean('emailVerified').notNull().default(false), image: text('image'), createdAt: timestamp('createdAt').notNull().defaultNow(), updatedAt: timestamp('updatedAt').notNull().defaultNow(),
})
export const session = pgTable('session', { id: text('id').primaryKey(), expiresAt: timestamp('expiresAt').notNull(), token: text('token').notNull().unique(), createdAt: timestamp('createdAt').notNull().defaultNow(), updatedAt: timestamp('updatedAt').notNull().defaultNow(), ipAddress: text('ipAddress'), userAgent: text('userAgent'), userId: text('userId').notNull() })
export const account = pgTable('account', { id: text('id').primaryKey(), accountId: text('accountId').notNull(), providerId: text('providerId').notNull(), userId: text('userId').notNull(), accessToken: text('accessToken'), refreshToken: text('refreshToken'), idToken: text('idToken'), accessTokenExpiresAt: timestamp('accessTokenExpiresAt'), refreshTokenExpiresAt: timestamp('refreshTokenExpiresAt'), scope: text('scope'), issuer: text('issuer'), password: text('password'), createdAt: timestamp('createdAt').notNull().defaultNow(), updatedAt: timestamp('updatedAt').notNull().defaultNow() })
export const verification = pgTable('verification', { id: text('id').primaryKey(), identifier: text('identifier').notNull(), value: text('value').notNull(), expiresAt: timestamp('expiresAt').notNull(), createdAt: timestamp('createdAt').defaultNow(), updatedAt: timestamp('updatedAt').defaultNow() })

export const tradingSettings = pgTable('trading_settings', { id: serial('id').primaryKey(), userId: text('user_id').notNull().unique(), initialBalance: numeric('initial_balance', { precision: 14, scale: 2 }).notNull().default('1000'), taxRate: numeric('tax_rate', { precision: 5, scale: 2 }).notNull().default('15'), dailyGoal: numeric('daily_goal', { precision: 14, scale: 2 }).notNull().default('100'), updatedAt: timestamp('updated_at').notNull().defaultNow() })
export const tradingPairs = pgTable('trading_pairs', { id: serial('id').primaryKey(), userId: text('user_id').notNull(), symbol: text('symbol').notNull(), createdAt: timestamp('created_at').notNull().defaultNow() })

export const trades = pgTable('trades', { id: serial('id').primaryKey(), userId: text('user_id').notNull(), tradedAt: timestamp('traded_at').notNull().defaultNow(), pair: text('pair').notNull(), direction: text('direction').notNull(), amount: numeric('amount', { precision: 14, scale: 2 }).notNull(), payout: numeric('payout', { precision: 5, scale: 2 }).notNull().default('85'), result: text('result').notNull(), profit: numeric('profit', { precision: 14, scale: 2 }).notNull(), mood: text('mood').notNull(), followedPlan: boolean('followed_plan').notNull().default(true), strategy: text('strategy'), notes: text('notes'), screenshotPath: text('screenshot_path'), createdAt: timestamp('created_at').notNull().defaultNow() })
