'use client'

import { useState } from 'react'
import Link from 'next/link'
import { useRouter } from 'next/navigation'
import { authClient } from '@/lib/auth-client'

export function AuthForm({ mode }: { mode: 'sign-in' | 'sign-up' }) {
  const router = useRouter(); const isSignUp = mode === 'sign-up'
  const [name,setName]=useState(''); const [email,setEmail]=useState(''); const [password,setPassword]=useState(''); const [error,setError]=useState<string | null>(null); const [loading,setLoading]=useState(false)
  async function submit(e: React.FormEvent) { e.preventDefault(); setLoading(true); setError(null); const result = isSignUp ? await authClient.signUp.email({name,email,password}) : await authClient.signIn.email({email,password}); setLoading(false); if (result.error) { setError('Não foi possível concluir. Confira seus dados e tente novamente.'); return }; router.push('/'); router.refresh() }
  return <main className="min-h-svh bg-background flex items-center justify-center px-4"><section className="w-full max-w-md rounded-2xl border border-border bg-card p-8 shadow-2xl"><div className="mb-8"><div className="mb-6 flex items-center gap-3"><div className="size-10 rounded-xl bg-primary flex items-center justify-center text-primary-foreground">↗</div><span className="font-semibold tracking-tight">Edge Journal</span></div><h1 className="text-2xl font-semibold">{isSignUp ? 'Crie sua conta' : 'Bem-vindo de volta'}</h1><p className="mt-2 text-sm text-muted-foreground">{isSignUp ? 'Comece a acompanhar sua consistência.' : 'Entre para acessar seu diário de trading.'}</p></div><form onSubmit={submit} className="flex flex-col gap-4">{isSignUp&&<label className="flex flex-col gap-2 text-sm">Nome<input value={name} onChange={e=>setName(e.target.value)} required autoComplete="name" className="h-11 rounded-lg border border-input bg-background px-3"/></label>}<label className="flex flex-col gap-2 text-sm">Email<input type="email" value={email} onChange={e=>setEmail(e.target.value)} required autoComplete="email" className="h-11 rounded-lg border border-input bg-background px-3"/></label><label className="flex flex-col gap-2 text-sm">Senha<input type="password" value={password} onChange={e=>setPassword(e.target.value)} required minLength={8} autoComplete={isSignUp?'new-password':'current-password'} className="h-11 rounded-lg border border-input bg-background px-3"/></label>{error&&<p role="alert" className="text-sm text-destructive">{error}</p>}<button disabled={loading} className="h-11 rounded-lg bg-primary font-semibold text-primary-foreground disabled:opacity-60">{loading?'Aguarde…':isSignUp?'Criar conta':'Entrar'}</button></form><p className="mt-6 text-center text-sm text-muted-foreground">{isSignUp?'Já possui uma conta?':'Ainda não possui uma conta?'} <Link className="font-medium text-primary hover:underline" href={isSignUp?'/sign-in':'/sign-up'}>{isSignUp?'Entrar':'Criar conta'}</Link></p></section></main>
}
