'use client'

import { useMemo, useState } from 'react'
import { BarChart3, Bell, CalendarDays, Check, ChevronDown, CircleDollarSign, FileText, Gauge, ImagePlus, LayoutDashboard, Moon, MoreHorizontal, Plus, Settings, Target, TrendingDown, TrendingUp, Trophy, Users, Wallet, X } from 'lucide-react'

type Trade = { pair: string; direction: 'CALL' | 'PUT'; result: 'win' | 'loss'; profit: number; mood: string; time: string; followed: boolean }
const pairs = ['EUR/USD','GBP/USD','USD/JPY','AUD/USD','USD/CAD','USD/CHF','EUR/GBP','EUR/JPY','GBP/JPY','NZD/USD','BTC/USD','Gold','US 500','US 30']
const money = (v:number) => new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}).format(v)

import { createTrade } from '@/app/actions/trading'

export function TradingDashboard({ user, initialData }: { user: { name: string; email: string }; initialData: { trades: any[]; settings: any } }){
 const [trades,setTrades]=useState<Trade[]>(initialData.trades.map((t:any)=>({pair:t.pair,direction:t.direction,result:t.result,profit:t.profit,mood:t.mood,time:new Date(t.tradedAt).toLocaleTimeString('pt-BR',{hour:'2-digit',minute:'2-digit'}),followed:t.followedPlan}))); const [open,setOpen]=useState(false); const [active,setActive]=useState('Visão geral')
 const total=trades.reduce((a,t)=>a+t.profit,0), wins=trades.filter(t=>t.result==='win').length, losses=trades.length-wins
 const winRate=Math.round((wins/trades.length)*100)
 const [form,setForm]=useState({pair:'EUR/USD',direction:'CALL',amount:'50',payout:'85',result:'win',mood:'Confiante',followed:'true',notes:''})
 const addTrade=async()=>{await createTrade({pair:form.pair,direction:form.direction,amount:Number(form.amount),payout:Number(form.payout),result:form.result,mood:form.mood,followedPlan:form.followed==='true',notes:form.notes});setOpen(false);window.location.reload()}
 const points=useMemo(()=>[42,48,45,58,55,68,65,78,74,88,84,96],[])
 return <div className="min-h-screen bg-background text-foreground flex">
  <aside className="hidden md:flex w-[76px] shrink-0 border-r border-border/60 bg-sidebar flex-col items-center py-5 gap-5">
   <div className="size-10 rounded-xl bg-primary flex items-center justify-center text-primary-foreground"><TrendingUp className="size-5"/></div>
   <div className="h-px w-9 bg-border/70"/>
   <nav className="flex flex-col gap-3">{[[LayoutDashboard,'Visão geral'],[BarChart3,'Análises'],[CalendarDays,'Calendário'],[Wallet,'Saldo'],[Target,'Metas'],[FileText,'Operações'],[Settings,'Configurações']].map(([Icon,label]:any)=><button key={label} onClick={()=>setActive(label)} title={label} className={`size-10 rounded-xl flex items-center justify-center transition-colors ${active===label?'bg-primary/15 text-primary':'text-muted-foreground hover:bg-muted hover:text-foreground'}`}><Icon className="size-[18px]"/></button>)}</nav>
   <div className="mt-auto flex flex-col gap-4 items-center"><button title="Notificações" className="text-muted-foreground hover:text-foreground"><Bell className="size-[18px]"/></button><button title="Modo escuro" className="text-muted-foreground hover:text-foreground"><Moon className="size-[18px]"/></button><div className="size-8 rounded-full bg-primary/20 text-primary text-xs font-semibold flex items-center justify-center">JS</div></div>
  </aside>
  <main className="flex-1 min-w-0"><header className="h-[74px] border-b border-border/60 flex items-center justify-between px-5 md:px-8"><div><p className="text-xs text-muted-foreground">Quarta-feira, 18 de junho de 2025</p><h1 className="text-xl font-semibold tracking-tight">Olá, João <span className="text-muted-foreground font-normal">— vamos revisar seu dia?</span></h1></div><div className="flex items-center gap-3"><button className="hidden sm:flex items-center gap-2 rounded-lg border border-border px-3 py-2 text-xs text-muted-foreground hover:bg-muted"><Settings className="size-3.5"/> Personalizar</button><button onClick={()=>setOpen(true)} className="flex items-center gap-2 rounded-lg bg-primary text-primary-foreground px-3.5 py-2 text-xs font-semibold hover:opacity-90"><Plus className="size-4"/> Nova operação</button></div></header>
   <div className="p-5 md:p-8 max-w-[1500px] mx-auto"><div className="flex items-center justify-between mb-6"><div><h2 className="text-2xl font-semibold">Visão geral</h2><p className="text-sm text-muted-foreground mt-1">Acompanhe sua consistência, não apenas o resultado.</p></div><button className="flex items-center gap-2 rounded-lg border border-border px-3 py-2 text-xs text-muted-foreground">Este mês <ChevronDown className="size-3.5"/></button></div>
    <section className="grid grid-cols-2 lg:grid-cols-4 gap-3 mb-4">{[['Saldo atual',money(1240+total),'+8,4%',CircleDollarSign,'positive'],['Resultado líquido',money(total),'+12,1%',TrendingUp,'positive'],['Taxa de acerto',`${winRate}%`,`${wins}W / ${losses}L`,Gauge,'blue'],['Aderência ao plano','92%','Excelente',Check,'purple']].map(([label,value,sub,Icon,tone]:any)=><div className="rounded-xl border border-border/70 bg-card p-4" key={label}><div className="flex items-center justify-between"><span className="text-xs text-muted-foreground">{label}</span><Icon className={`size-4 ${tone==='positive'?'text-emerald-400':tone==='blue'?'text-primary':'text-violet-400'}`}/></div><p className="text-2xl font-semibold mt-3 tracking-tight">{value}</p><p className={`text-xs mt-1 ${tone==='positive'?'text-emerald-400':tone==='blue'?'text-primary':'text-violet-400'}`}>{sub}</p></div>)}</section>
    <section className="grid lg:grid-cols-[1.7fr_1fr] gap-4 mb-4"><div className="rounded-xl border border-border/70 bg-card p-5"><div className="flex items-center justify-between mb-4"><div><h3 className="font-medium">Evolução do saldo</h3><p className="text-xs text-muted-foreground mt-1">Últimos 12 dias de operação</p></div><div className="text-right"><p className="text-lg font-semibold text-emerald-400">{money(1240+total)}</p><p className="text-xs text-emerald-400">+8,4% no período</p></div></div><div className="h-[190px] relative"><div className="absolute inset-0 flex flex-col justify-between text-[10px] text-muted-foreground/60"><span>R$ 1.400</span><span>R$ 1.200</span><span>R$ 1.000</span><span>R$ 800</span></div><svg className="absolute inset-0 left-12 w-[calc(100%-3rem)] h-full overflow-visible" viewBox="0 0 600 180" preserveAspectRatio="none"><defs><linearGradient id="area" x1="0" x2="0" y1="0" y2="1"><stop offset="0" stopColor="currentColor" stopOpacity=".18"/><stop offset="1" stopColor="currentColor" stopOpacity="0"/></linearGradient></defs><path d={`M 0 ${180-points[0]*1.5} ${points.map((p,i)=>`L ${(i/(points.length-1))*600} ${180-p*1.5}`).join(' ')} L 600 180 L 0 180 Z`} fill="url(#area)" className="text-primary"/><path d={`M 0 ${180-points[0]*1.5} ${points.map((p,i)=>`L ${(i/(points.length-1))*600} ${180-p*1.5}`).join(' ')}`} fill="none" stroke="currentColor" strokeWidth="2.5" vectorEffect="non-scaling-stroke" className="text-primary"/></svg></div><div className="ml-12 flex justify-between text-[10px] text-muted-foreground mt-2"><span>03 jun</span><span>07 jun</span><span>11 jun</span><span>15 jun</span><span>18 jun</span></div></div>
     <div className="rounded-xl border border-border/70 bg-card p-5"><div className="flex items-center justify-between mb-4"><div><h3 className="font-medium">Seu estado hoje</h3><p className="text-xs text-muted-foreground mt-1">Como você está operando?</p></div><span className="text-2xl">◎</span></div><div className="rounded-lg bg-muted/60 p-4 mb-4"><p className="text-sm font-medium">Calmo e focado</p><p className="text-xs text-muted-foreground mt-1">Você seguiu seu plano em 4 de 5 operações.</p></div><div className="grid grid-cols-4 gap-2">{['Confiante','Calma','Neutra','Ansiosa'].map((m,i)=><button key={m} className={`rounded-lg border px-1 py-2 text-[10px] ${i===1?'border-primary bg-primary/10 text-primary':'border-border text-muted-foreground hover:bg-muted'}`}><span className="block text-base mb-1">{['◉','◌','○','◍'][i]}</span>{m}</button>)}</div></div></section>
    <section className="grid md:grid-cols-3 gap-4 mb-4"><div className="rounded-xl border border-border/70 bg-card p-5 md:col-span-2"><div className="flex items-center justify-between mb-4"><div><h3 className="font-medium">Calendário de resultados</h3><p className="text-xs text-muted-foreground mt-1">Lucro e prejuízo por dia</p></div><button className="text-muted-foreground"><MoreHorizontal className="size-4"/></button></div><div className="grid grid-cols-7 gap-2 text-center text-[10px]">{['SEG','TER','QUA','QUI','SEX','SÁB','DOM'].map(d=><span className="text-muted-foreground py-1" key={d}>{d}</span>)}{Array.from({length:28},(_,i)=>{const v=[0,45,0,-30,80,120,0,65,-50,0,90,0,42,110,-20,0,75,60,0,-40,100,0,85,0,50,120,0,0][i];return <div key={i} className={`rounded-lg py-2 border ${v>0?'bg-emerald-500/10 border-emerald-500/20 text-emerald-400':v<0?'bg-red-500/10 border-red-500/20 text-red-400':'bg-muted/30 border-border/50 text-muted-foreground'}`}><span className="block">{i+1}</span>{v!==0&&<span className="block text-[9px] mt-1">{v>0?'+':''}{v}</span>}</div>})}</div></div><div className="rounded-xl border border-border/70 bg-card p-5"><h3 className="font-medium">Resumo do mês</h3><div className="flex flex-col gap-4 mt-5">{[['Operações',trades.length,'text-foreground'],['Vitórias',wins,'text-emerald-400'],['Derrotas',losses,'text-red-400'],['Média por trade',money(total/trades.length),'text-primary']].map(([l,v,c]:any)=><div className="flex items-center justify-between" key={l}><span className="text-xs text-muted-foreground">{l}</span><span className={`text-sm font-semibold ${c}`}>{v}</span></div>)}</div><div className="h-2 bg-muted rounded-full mt-6 overflow-hidden"><div className="h-full bg-emerald-500 rounded-full" style={{width:`${winRate}%`}}/></div><p className="text-[11px] text-muted-foreground mt-2">Meta mensal: R$ 500 <span className="float-right">{Math.round(total/5*100)}%</span></p></div></section>
    <section className="rounded-xl border border-border/70 bg-card"><div className="p-5 flex items-center justify-between border-b border-border/60"><div><h3 className="font-medium">Operações recentes</h3><p className="text-xs text-muted-foreground mt-1">Seu diário de hoje</p></div><button onClick={()=>setOpen(true)} className="text-xs text-primary hover:underline">Ver todas</button></div><div className="divide-y divide-border/50">{trades.slice(0,5).map((t,i)=><div key={i} className="flex items-center gap-3 px-5 py-3"><div className={`size-8 rounded-lg flex items-center justify-center ${t.result==='win'?'bg-emerald-500/10 text-emerald-400':'bg-red-500/10 text-red-400'}`}>{t.result==='win'?<TrendingUp className="size-4"/>:<TrendingDown className="size-4"/>}</div><div className="min-w-0 flex-1"><div className="flex items-center gap-2"><span className="text-sm font-medium">{t.pair}</span><span className="text-[10px] rounded bg-muted px-1.5 py-0.5 text-muted-foreground">{t.direction}</span></div><p className="text-xs text-muted-foreground mt-0.5">{t.time} · {t.mood} · {t.followed?'Seguiu o plano':'Fora do plano'}</p></div><span className={`text-sm font-semibold ${t.profit>0?'text-emerald-400':'text-red-400'}`}>{t.profit>0?'+':''}{money(t.profit)}</span><ImagePlus className="size-4 text-muted-foreground/50"/></div>)}</div></section>
    <section className="mt-4 rounded-xl border border-amber-500/20 bg-amber-500/5 p-4 flex gap-3"><FileText className="size-4 text-amber-400 mt-0.5 shrink-0"/><div><p className="text-xs font-medium text-amber-300">Estimativa de imposto</p><p className="text-xs text-muted-foreground mt-1">Com base no seu resultado líquido de {money(total)}, sua estimativa mensal (alíquota configurável de 15%) é <span className="text-foreground font-medium">{money(Math.max(total,0)*.15)}</span>. Este cálculo é informativo e não substitui orientação contábil.</p></div><button className="ml-auto text-muted-foreground"><X className="size-4"/></button></section>
   </div></main>
   {open&&<div className="fixed inset-0 bg-background/80 backdrop-blur-sm flex items-center justify-center p-4 z-50"><div className="w-full max-w-lg rounded-2xl border border-border bg-card shadow-2xl"><div className="flex items-center justify-between p-5 border-b border-border"><div><h2 className="font-semibold">Registrar operação</h2><p className="text-xs text-muted-foreground mt-1">Anote o contexto, não só o resultado.</p></div><button onClick={()=>setOpen(false)} className="text-muted-foreground hover:text-foreground"><X className="size-5"/></button></div><div className="p-5 grid grid-cols-2 gap-4 max-h-[70vh] overflow-y-auto">{[['Par','pair'],['Direção','direction'],['Resultado','result'],['Humor','mood'],['Valor investido','amount'],['Payout (%)','payout']].map(([label,key]:any)=><label className="flex flex-col gap-2 text-xs text-muted-foreground" key={key}>{label}{key==='pair'?<select value={form.pair} onChange={e=>setForm({...form,pair:e.target.value})} className="h-10 rounded-lg border border-input bg-background px-3 text-sm text-foreground">{pairs.map(p=><option key={p}>{p}</option>)}</select>:key==='direction'||key==='result'||key==='mood'?<select value={(form as any)[key]} onChange={e=>setForm({...form,[key]:e.target.value})} className="h-10 rounded-lg border border-input bg-background px-3 text-sm text-foreground">{(key==='direction'?['CALL','PUT']:key==='result'?['win','loss']:['Confiante','Calma','Neutra','Ansiosa']).map((x)=><option key={x}>{x}</option>)}</select>:<input type="number" value={(form as any)[key]} onChange={e=>setForm({...form,[key]:e.target.value})} className="h-10 rounded-lg border border-input bg-background px-3 text-sm text-foreground"/>}</label>)}<label className="col-span-2 flex items-center gap-3 text-sm text-foreground"><input type="checkbox" checked={form.followed==='true'} onChange={e=>setForm({...form,followed:String(e.target.checked)})} className="accent-primary"/> Segui meu operacional nesta entrada</label><label className="col-span-2 flex flex-col gap-2 text-xs text-muted-foreground">Observações<textarea value={form.notes} onChange={e=>setForm({...form,notes:e.target.value})} placeholder="O que você viu? Como se sentiu?" className="min-h-20 rounded-lg border border-input bg-background p-3 text-sm text-foreground resize-none"/></label><button className="col-span-2 h-10 rounded-lg border border-dashed border-border text-xs text-muted-foreground hover:bg-muted flex items-center justify-center gap-2"><ImagePlus className="size-4"/> Anexar screenshot</button></div><div className="p-5 pt-0 flex justify-end gap-2"><button onClick={()=>setOpen(false)} className="px-4 py-2 rounded-lg text-xs text-muted-foreground hover:bg-muted">Cancelar</button><button onClick={addTrade} className="px-4 py-2 rounded-lg bg-primary text-primary-foreground text-xs font-semibold">Salvar operação</button></div></div></div>}
 </div>
}

export default TradingDashboard
