'use client'

import { useMemo, useState } from 'react'
import { signOut } from '@/lib/auth-client'
import { createTrade } from '@/app/actions/trading'
import { BarChart3, CalendarDays, Check, CircleDollarSign, FileText, LayoutDashboard, LogOut, Moon, Plus, Settings, Target, TrendingDown, TrendingUp, Wallet, X } from 'lucide-react'

type Trade = { id:number; pair:string; direction:string; result:string; profit:number; mood:string; tradedAt:string; followedPlan:boolean }
const pairs = ['EUR/USD','GBP/USD','USD/JPY','AUD/USD','USD/CAD','USD/CHF','EUR/GBP','EUR/JPY','GBP/JPY','NZD/USD','BTC/USD','Gold','US 500','US 30']
const money = (v:number) => new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'}).format(v)

export function TradingDashboard({user,initialData}:{user:{name:string;email:string};initialData:{trades:Trade[];settings:any}}) {
 const [trades,setTrades]=useState(initialData.trades); const [open,setOpen]=useState(false); const [saving,setSaving]=useState(false); const [mood,setMood]=useState('Calmo');
 const [form,setForm]=useState({pair:'EUR/USD',direction:'CALL',amount:'50',payout:'85',result:'win',mood:'Confiante',followedPlan:'true',notes:''})
 const initial=Number(initialData.settings?.initialBalance??0), tax=Number(initialData.settings?.taxRate??15), goal=Number(initialData.settings?.dailyGoal??0)
 const total=trades.reduce((a,t)=>a+Number(t.profit),0), wins=trades.filter(t=>t.result==='win').length, losses=trades.filter(t=>t.result==='loss').length, rate=trades.length?Math.round(wins/trades.length*100):0, adherence=trades.length?Math.round(trades.filter(t=>t.followedPlan).length/trades.length*100):0
 const balance=initial+total, avg=trades.length?total/trades.length:0
 const chart=useMemo(()=>[0,...trades.slice().reverse().map((_,i)=>trades.slice().reverse().slice(0,i+1).reduce((s,t)=>s+Number(t.profit),0))],[trades])
 async function add(){setSaving(true);try{await createTrade({pair:form.pair,direction:form.direction,amount:Number(form.amount),payout:Number(form.payout),result:form.result,mood:form.mood,followedPlan:form.followedPlan==='true',notes:form.notes});window.location.reload()}finally{setSaving(false)}}
 async function logout(){await signOut();window.location.href='/sign-in'}
 return <div className="min-h-screen bg-background text-foreground flex">
  <aside className="hidden md:flex w-[76px] shrink-0 border-r border-border/60 bg-sidebar flex-col items-center py-5 gap-5"><div className="size-10 rounded-xl bg-primary flex items-center justify-center text-primary-foreground"><TrendingUp className="size-5"/></div><div className="h-px w-9 bg-border/70"/><nav className="flex flex-col gap-3">{[[LayoutDashboard,'Visão geral'],[BarChart3,'Análises'],[CalendarDays,'Calendário'],[Wallet,'Saldo'],[Target,'Metas'],[FileText,'Operações'],[Settings,'Configurações']].map(([Icon,label]:any)=><button key={label} title={label} className="size-10 rounded-xl flex items-center justify-center text-muted-foreground hover:bg-muted hover:text-foreground"><Icon className="size-[18px]"/></button>)}</nav><div className="mt-auto flex flex-col gap-5 items-center"><button title="Modo escuro"><Moon className="size-[18px] text-muted-foreground"/></button><button title="Sair" onClick={logout} className="text-muted-foreground hover:text-destructive"><LogOut className="size-[18px]"/></button><div className="size-8 rounded-full bg-primary/20 text-primary text-xs font-semibold flex items-center justify-center">{user.name.slice(0,2).toUpperCase()}</div></div></aside>
  <main className="flex-1 min-w-0"><header className="h-[74px] border-b border-border/60 flex items-center justify-between px-5 md:px-8"><div><p className="text-xs text-muted-foreground">{new Intl.DateTimeFormat('pt-BR',{dateStyle:'full'}).format(new Date())}</p><h1 className="text-xl font-semibold">Olá, {user.name} <span className="text-muted-foreground font-normal">— vamos revisar seu dia?</span></h1></div><div className="flex items-center gap-3"><button onClick={logout} className="hidden sm:flex items-center gap-2 rounded-lg border border-border px-3 py-2 text-xs text-muted-foreground hover:bg-muted"><LogOut className="size-3.5"/> Sair</button><button onClick={()=>setOpen(true)} className="flex items-center gap-2 rounded-lg bg-primary text-primary-foreground px-3.5 py-2 text-xs font-semibold"><Plus className="size-4"/> Nova operação</button></div></header>
   <div className="p-5 md:p-8 max-w-[1500px] mx-auto"><div className="flex items-center justify-between mb-6"><div><h2 className="text-2xl font-semibold">Visão geral</h2><p className="text-sm text-muted-foreground mt-1">Dados reais da sua conta, sem resultados pré-preenchidos.</p></div><span className="text-xs text-muted-foreground">{trades.length} operações registradas</span></div>
    <section className="grid grid-cols-2 lg:grid-cols-4 gap-3 mb-4">{[['Saldo atual',money(balance),initial?`${total>=0?'+':''}${money(total)}`:'Configure seu saldo',CircleDollarSign,'text-emerald-400'],['Resultado líquido',money(total),trades.length?`${wins} vitórias · ${losses} derrotas`:'Nenhuma operação',TrendingUp,'text-emerald-400'],['Taxa de acerto',`${rate}%`,`${wins}W / ${losses}L`,Target,'text-primary'],['Aderência ao plano',`${adherence}%`,trades.length?'Baseado nas operações':'Nenhum dado ainda',Check,'text-violet-400']].map(([l,v,s,I,c]:any)=><div className="rounded-xl border border-border/70 bg-card p-4" key={l}><div className="flex justify-between"><span className="text-xs text-muted-foreground">{l}</span><I className={`size-4 ${c}`}/></div><p className="text-2xl font-semibold mt-3">{v}</p><p className={`text-xs mt-1 ${c}`}>{s}</p></div>)}</section>
    <section className="grid lg:grid-cols-[1.7fr_1fr] gap-4 mb-4"><div className="rounded-xl border border-border/70 bg-card p-5"><div className="flex justify-between mb-4"><div><h3 className="font-medium">Evolução do saldo</h3><p className="text-xs text-muted-foreground mt-1">Baseado nas suas operações</p></div><strong className="text-emerald-400">{money(balance)}</strong></div>{trades.length?<div className="h-[190px] flex items-end gap-1 border-b border-border/60">{chart.map((v,i)=><div key={i} className="flex-1 bg-primary/60 rounded-t-sm min-h-1" style={{height:`${Math.max(3,((v-Math.min(...chart))/(Math.max(...chart)-Math.min(...chart)||1))*100)}%`}} title={money(initial+v)}/>)}</div>:<div className="h-[190px] grid place-items-center text-sm text-muted-foreground">Registre sua primeira operação para visualizar a evolução.</div>}</div>
     <div className="rounded-xl border border-border/70 bg-card p-5"><h3 className="font-medium">Seu estado hoje</h3><p className="text-xs text-muted-foreground mt-1">Como você está operando?</p><div className="rounded-lg bg-muted/60 p-4 my-4"><p className="text-sm font-medium">{mood}</p><p className="text-xs text-muted-foreground mt-1">{trades.length?`Você seguiu seu plano em ${adherence}% das operações.`:'Registre o humor em cada operação.'}</p></div><div className="grid grid-cols-2 gap-2">{['Confiante','Calmo','Neutra','Ansiosa'].map(m=><button key={m} onClick={()=>setMood(m)} className={`rounded-lg border px-2 py-3 text-xs ${mood===m?'border-primary bg-primary/10 text-primary':'border-border text-muted-foreground'}`}>{m}</button>)}</div></div></section>
    <section className="grid md:grid-cols-3 gap-4 mb-4"><div className="rounded-xl border border-border/70 bg-card p-5 md:col-span-2"><h3 className="font-medium">Calendário de resultados</h3><p className="text-xs text-muted-foreground mt-1 mb-4">Lucro e prejuízo por dia</p><div className="grid grid-cols-7 gap-2 text-center text-[10px]">{['SEG','TER','QUA','QUI','SEX','SÁB','DOM'].map(d=><span className="text-muted-foreground py-1" key={d}>{d}</span>)}{Array.from({length:28},(_,i)=>{const day=trades.filter(t=>new Date(t.tradedAt).getDate()===i+1).reduce((s,t)=>s+Number(t.profit),0);return <div key={i} className={`rounded-lg py-2 border ${day>0?'bg-emerald-500/10 border-emerald-500/20 text-emerald-400':day<0?'bg-red-500/10 border-red-500/20 text-red-400':'bg-muted/30 border-border/50 text-muted-foreground'}`}><span className="block">{i+1}</span>{day!==0&&<span className="block mt-1">{day>0?'+':''}{money(day)}</span>}</div>})}</div></div><div className="rounded-xl border border-border/70 bg-card p-5"><h3 className="font-medium">Resumo do mês</h3><div className="flex flex-col gap-4 mt-5">{[['Operações',trades.length],['Vitórias',wins],['Derrotas',losses],['Média por trade',money(avg)]].map(([l,v]:any)=><div className="flex justify-between" key={l}><span className="text-xs text-muted-foreground">{l}</span><strong className="text-sm">{v}</strong></div>)}</div><div className="h-2 bg-muted rounded-full mt-6"><div className="h-full bg-emerald-500 rounded-full" style={{width:`${rate}%`}}/></div><p className="text-[11px] text-muted-foreground mt-2">Meta mensal: {money(goal)}</p></div></section>
    <section className="rounded-xl border border-border/70 bg-card"><div className="p-5 border-b border-border/60"><h3 className="font-medium">Operações recentes</h3><p className="text-xs text-muted-foreground mt-1">Seu diário de hoje</p></div>{trades.length?<div className="divide-y divide-border/50">{trades.slice(0,8).map(t=><div key={t.id} className="flex items-center gap-3 px-5 py-3"><div className={`size-8 rounded-lg flex items-center justify-center ${t.result==='win'?'bg-emerald-500/10 text-emerald-400':'bg-red-500/10 text-red-400'}`}>{t.result==='win'?<TrendingUp className="size-4"/>:<TrendingDown className="size-4"/>}</div><div className="flex-1"><span className="text-sm font-medium">{t.pair}</span><p className="text-xs text-muted-foreground">{new Date(t.tradedAt).toLocaleTimeString('pt-BR',{hour:'2-digit',minute:'2-digit'})} · {t.mood} · {t.followedPlan?'Seguiu o plano':'Fora do plano'}</p></div><strong className={Number(t.profit)>=0?'text-emerald-400':'text-red-400'}>{Number(t.profit)>=0?'+':''}{money(Number(t.profit))}</strong></div>)}</div>:<div className="p-8 text-center text-sm text-muted-foreground">Nenhuma operação registrada. Clique em “Nova operação” para começar.</div>}</section>
    <section className="mt-4 rounded-xl border border-amber-500/20 bg-amber-500/5 p-4 flex gap-3"><FileText className="size-4 text-amber-400 shrink-0"/><p className="text-xs text-muted-foreground">Estimativa informativa de imposto: {money(Math.max(total,0)*tax/100)} ({tax}%). Não substitui orientação contábil.</p></section>
   </div></main>
   {open&&<div className="fixed inset-0 bg-background/80 backdrop-blur-sm flex items-center justify-center p-4 z-50"><div className="w-full max-w-lg rounded-2xl border border-border bg-card shadow-2xl"><div className="flex justify-between p-5 border-b border-border"><div><h2 className="font-semibold">Registrar operação</h2><p className="text-xs text-muted-foreground mt-1">Salva diretamente no Neon.</p></div><button onClick={()=>setOpen(false)}><X className="size-5 text-muted-foreground"/></button></div><div className="p-5 grid grid-cols-2 gap-4 max-h-[70vh] overflow-y-auto">{[['Par','pair'],['Direção','direction'],['Resultado','result'],['Humor','mood'],['Valor investido','amount'],['Payout (%)','payout']].map(([label,key]:any)=><label key={key} className="flex flex-col gap-2 text-xs text-muted-foreground">{label}<select value={(form as any)[key]} onChange={e=>setForm({...form,[key]:e.target.value})} className="h-10 rounded-lg border border-input bg-background px-3 text-sm text-foreground">{(key==='pair'?pairs:key==='direction'?['CALL','PUT']:key==='result'?['win','loss','break_even']:['Confiante','Calmo','Neutra','Ansiosa']).map((x:string)=><option key={x}>{x}</option>)}</select></label>)}<label className="flex items-center gap-2 col-span-2 text-sm"><input type="checkbox" checked={form.followedPlan==='true'} onChange={e=>setForm({...form,followedPlan:String(e.target.checked)})}/> Segui meu operacional</label><button disabled={saving} onClick={add} className="col-span-2 h-11 rounded-lg bg-primary text-primary-foreground font-semibold disabled:opacity-50">{saving?'Salvando…':'Salvar operação'}</button></div></div></div>}
 </div>
}
export default TradingDashboard
